// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tacpsznnvpqitrlhgrgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhY3Bzem5udnBxaXRybGhncmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzY5OTQsImV4cCI6MjA2NjAxMjk5NH0.P44tEB2ygUkxk1yeV5ap5ezsff5QgQxxzn1AKqRhSDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);